### ISSUE TITLE
Create a sweet icon

### ISSUE THREAD

**Issue by the-hobbes** [the-hobbes/website_time_tracker#11]
Make an icon for the chrome extension.

**Comment by the-hobbes** [comment]
@jonedm wanna take this one?

**Comment by jonedm** [comment]
@the-hobbes here is version 01 of an icon I made for the project. My first instinct was to make a half clock half pie chart. For the next version I want to refine the geometry, explore color possibilities, and try a different placement of the cut away. Let me know what you think.
![icon](https://cloud.githubusercontent.com/assets/11955744/7211650/f1bbca46-e511-11e4-9f67-b7185e9484f9.png)

**Comment by the-hobbes** [comment]
looks awesome! do you want to add it to the repo, or do you want me to do it?
