### ISSUE TITLE
Pie Chart

### ISSUE THREAD

**Issue by the-hobbes** [the-hobbes/website_time_tracker#2]
Add a pie chart that shows you what percentage of the top 10 websites you visited takes up of the whole week of history. 

https://google-developers.appspot.com/chart/interactive/docs/gallery/piechart

**Comment by the-hobbes** [comment]
Can't use google charts for this, unless I use an iframe and write up a webapp hosted somewhere. 

http://stackoverflow.com/questions/15348868/google-chart-in-chrome-extension-popup

**Comment by the-hobbes** [comment]
Since I'm exploring the iFrame/webapp route, what is the best way to get unique charts back? I want each person who uses the chrome extension to send their own data to the api endpoint on the webapp, then generate a chart of each of those datasets and put it up somewhere where the iframe can point to it.

Maybe I could generate a random url, then pass it back in a return from the chrome javascript call, then use javascript to set the url of the iframe to match that random url and get the unique chart for that person? Any thoughts or ideas, @EdgeCaseBerg?

**Comment by the-hobbes** [comment]
This was suggested to me: http://d3js.org/

Download the minified library, and add it to the chrome extension.

**Comment by EdgeCaseBerg** [comment]
D3 is really really really powerful. But you need to read about data binding and joining first to fully understand it. There's a lot of good tutorials out there. Looking through my bookmarks real fast, this [one comes to mind](http://code.hazzens.com/d3tut/lesson_4.html). And of course, you can read from the master himself, [here](http://bost.ocks.org/mike/join/)

I know I sent a couple really good ones to @gfritz before so I'll have to hunt through my email for them. One of them explains things quite well and had great visualizations that really cleared everything up.

Why do you want to generate a chart on the server in an iframe? Why not just generate one on the app itself?

**Comment by the-hobbes** [comment]
This is pretty much all I want to do: http://nvd3.org/examples/pie.html

**Comment by the-hobbes** [comment]
@theluisnin (who suggested d3) also provided this tutorial: http://code.hazzens.com/d3tut/lesson_1.html

**Comment by EdgeCaseBerg** [comment]
Yeah, SVG's  are your way to go if you want something simple. 
This is the tutorial that really helped make things click for me: http://bost.ocks.org/mike/nest/

**Comment by the-hobbes** [comment]
This is now working as of commit #f1efad0c60, although it still looks like crap. Further enhancements will be opened for prettification + css shenanigans. Thanks for your advice all!
